import Head from 'next/head'
import { useState } from 'react'
import Banner from '../components/Banner'
import NFTSet from '../components/NFTSet'

export default function Home({products}) {
  return (
    <div>
      
      <Head>
        <title>NFT marketplace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Banner data={products[0]} />

        <NFTSet data={products.slice(1,4)} />
        <NFTSet data={products.slice(4,7)} />
      
      </main>

   
    </div>
  )
}

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export async function getStaticProps() {

  // Fetch products data for the landing page by request to "http://localhost:3000/api/products" route.
  const products = await fetch("http://localhost:3000/api/products").then(res => res.json())

  return {
    props: {
      products,
    },
  }
}