import Head from 'next/head'
import Banner from '../components/Banner'
import NFT3D from '../components/NFT3D'

export default function Home({products}) {

  return (
    <div>
      
      <Head>
        <title>FreeFlow</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>

        {/* Landing Page Banner */}
        <div className='flex justify-between items-center'>
          <Banner />
          <NFT3D data={products[0]} />
        </div>

        {/* NFTSets */}
        <div className='grid grid-cols-2 place-items-center w-full'>
          {products.slice(1,).map((nftData,index ) => (
              <NFT3D data={nftData} key={index} />
            )
          )}
           
        </div>     



      </main>

   
    </div>
  )
}

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export async function getStaticProps() {
  // Fetch products data for the landing page by request to "http://localhost:3000/api/products" route.
  const products = await fetch("http://localhost:3000/api/products").then(res => res.json())
  return {
    props: {
      products
    },
  }
}