import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar"
import Banner from '../components/Banner'

export default function Home() {
  return (
    <div>
      
      <Head>
        <title>NFT marketplace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Banner />
      </main>

   
    </div>
  )
}
