/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: junior.phillip (https://sketchfab.com/junior.phillip)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/eth-coin-e6bd61ef2fa54308ba0ef65507ead9c9
title: ETH Coin
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3Dmodel/ethereum.gltf')
  const { actions } = useAnimations(animations, group)
  
  // Subscribe this component to the render-loop, rotate the mesh every frame
  useFrame((state, delta) => {
    if (props.rotate) {
        return (group.current.rotation.y += 0.008)
    }
  });
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="Cone_2" position={[0, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3Dmodel/ethereum.gltf')
