/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rtql8d (https://sketchfab.com/rtql8d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ledger-nano-s-48460b4b82724e9b8d03c0c3574793a5
title: Ledger Nano S
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/3Dmodel/ledger_nano_s.gltf')
  // Subscribe this component to the render-loop, rotate the mesh every frame
  useFrame((state, delta) => {
    if (props.rotate) {
        return (group.current.rotation.z += 0.008)
    }
  });
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={6}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials['Glass_-_Heavy_Color']} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials['Stainless_Steel_-_Brushed_Linear_Long']} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials['Plastic_-_Matte_Black']} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials['Steel_-_Satin']} />
      </group>
    </group>
  )
}

useGLTF.preload('/3Dmodel/ledger_nano_s.gltf')
