/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: pewcus-tunbek-4Buvso (https://sketchfab.com/pewcus-tunbek-4Buvso)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/macbook-air-m1-chip-silver-5b40cae179e745ea96cb9d409812a024
title: Macbook Air M1 Chip Silver
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/3Dmodel/macbook.gltf')
  
  // Subscribe this component to the render-loop, rotate the mesh every frame
  useFrame((state, delta) => {
    if (props.rotate) {
        return (group.current.rotation.y += 0.008)
    }
  });
  

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
          <mesh geometry={nodes.BzNfMMFMUvENCVB.geometry} material={nodes.BzNfMMFMUvENCVB.material} />
          <mesh geometry={nodes.vAGUyiVXfoNCfiz.geometry} material={materials.TQlUdQskMqFOeNF} />
          <mesh geometry={nodes.knmwBVvqKBprdhy.geometry} material={materials.ulJMfFlutqmNQMW} />
          <mesh geometry={nodes.IYquytLCepLmUBo.geometry} material={materials.XmFnkDCORGzfeME} />
          <mesh geometry={nodes.XzIjLarnJovNeFY.geometry} material={materials.RyMGdvvvrICYPYi} />
          <mesh geometry={nodes.TyqbjvAzBnHiKwb.geometry} material={materials.QvIzXEFfzNggOmB} />
          <mesh geometry={nodes.DghamaUxTHefQMN.geometry} material={nodes.DghamaUxTHefQMN.material} />
          <mesh geometry={nodes.wBBInSfLdDJGZAT.geometry} material={materials.fNwAJBobjIFRfvB} />
          <mesh geometry={nodes.MufZdDNbnijUuDI.geometry} material={materials.ZRtDNbbFJTtCHrm} />
          <mesh geometry={nodes.dzdDbHwlhsKhKXE.geometry} material={materials.sQFBWaBkjsgwGvu} />
          <mesh geometry={nodes.zmyDIvIISmVcrBw.geometry} material={materials.FXtoXdXSZfIeavz} />
          <mesh geometry={nodes.QFkVghDULzcFGVS.geometry} material={materials.oERDOwdFTcMQzDv} />
          <mesh geometry={nodes.DBvXeGikYLUKwdH.geometry} material={nodes.DBvXeGikYLUKwdH.material} />
          <mesh geometry={nodes.AwlBoBERHXitENF.geometry} material={nodes.AwlBoBERHXitENF.material} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV.geometry} material={materials.zSTXkYgEDkTgmAG} />
          <mesh geometry={nodes.efIPqtkSgQqIhbu.geometry} material={materials.stkDfiDJRcgomRA} />
          <mesh geometry={nodes.myHPgRcFLsxMInV.geometry} material={nodes.myHPgRcFLsxMInV.material} />
          <mesh geometry={nodes.vmspsaCrmgKKjDd.geometry} material={nodes.vmspsaCrmgKKjDd.material} />
          <mesh geometry={nodes.chqYjnnQUYDygUd.geometry} material={materials.FxVDqFpCAhktJsF} />
          <mesh geometry={nodes.ZbOWBLfcdfJLGbf.geometry} material={nodes.ZbOWBLfcdfJLGbf.material} />
          <mesh geometry={nodes.qtSHRxgTTtHDvvz.geometry} material={materials.uzwDFWlQEbgKaKk} />
          <mesh geometry={nodes.GuLDLtucEkhptAy.geometry} material={materials.TUaXhUUzDBaiMXN} />
          <mesh geometry={nodes.iPaYIdfHAoErrDD.geometry} material={materials.HOLRHAuxFvQaQOG} />
          <mesh geometry={nodes.tJeThulAohRVCYu.geometry} material={materials.vfSIsEZWCUAlBZY} />
          <mesh geometry={nodes.XqwOTtPISptJqzk.geometry} material={nodes.XqwOTtPISptJqzk.material} />
          <mesh geometry={nodes.vyTbhVpPBeJrZxo.geometry} material={nodes.vyTbhVpPBeJrZxo.material} />
          <mesh geometry={nodes.AUMLEhzRIkXUmsX.geometry} material={nodes.AUMLEhzRIkXUmsX.material} />
          <mesh geometry={nodes.TkULcWkLJtogGVS.geometry} material={nodes.TkULcWkLJtogGVS.material} />
          <mesh geometry={nodes.xJpdzOlweWAHqYU.geometry} material={nodes.xJpdzOlweWAHqYU.material} />
          <mesh geometry={nodes.TFsPkHBGmohYDUF.geometry} material={nodes.TFsPkHBGmohYDUF.material} />
          <mesh geometry={nodes.pcpUMJfNezWkOrK.geometry} material={nodes.pcpUMJfNezWkOrK.material} />
          <mesh geometry={nodes.vCoMumYuFVRrDxl.geometry} material={nodes.vCoMumYuFVRrDxl.material} />
          <mesh geometry={nodes.HzLAtwpaEQrTUta.geometry} material={nodes.HzLAtwpaEQrTUta.material} />
          <mesh geometry={nodes.tThJTMCDmnrUEvB.geometry} material={nodes.tThJTMCDmnrUEvB.material} />
          <mesh geometry={nodes.MXSRHoWxOJGMjpX.geometry} material={nodes.MXSRHoWxOJGMjpX.material} />
          <mesh geometry={nodes.NZXezpncDrTVPYd.geometry} material={nodes.NZXezpncDrTVPYd.material} />
          <mesh geometry={nodes.NfMmOpMNmolpLfw.geometry} material={nodes.NfMmOpMNmolpLfw.material} />
          <mesh geometry={nodes.TVhBYZaRqtFURFF.geometry} material={nodes.TVhBYZaRqtFURFF.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3Dmodel/macbook.gltf')
