/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cs-boy (https://sketchfab.com/cs-boy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nft-logo-1ef9b4ad52aa4ef69dfda0eea6cf1395
title: NFT Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/3Dmodel/nftLogo.gltf')
  // Subscribe this component to the render-loop, rotate the mesh every frame
  useFrame((state, delta) => {
    if (props.rotate) {
        return (group.current.rotation.y += 0.01)
    }
  });
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={8}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/3Dmodel/nftLogo.gltf')
