/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: C.K (https://sketchfab.com/buicongkhai92)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/squid-game-man-ce9f3c8d3bcb4049bc5090925a578446
title: Squid Game Man
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/3Dmodel/squid_game.gltf')
  // Subscribe this component to the render-loop, rotate the mesh every frame
  useFrame((state, delta) => {
    if (props.rotate) {
        return (group.current.rotation.y += 0.008)
    }
  });
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.02, -1.07, -0.02]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <group rotation={[0, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube007_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube007_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube007_Material002_0.geometry} material={materials['Material.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3Dmodel/squid_game.gltf')
