/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Flenehens (https://sketchfab.com/Flenehens)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/uniswap-cbc5410b87ba4f1099fa993c4225d38f
title: Uniswap
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/3Dmodel/uniswap.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.05, -0.03]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[723.27, -1.21, -0.66]} scale={8}>
            <mesh
              geometry={nodes.Uniswap_Baked_Uniswap_Bake1_baked_0.geometry}
              material={materials.Uniswap_Bake1_baked}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3Dmodel/uniswap.gltf')
